version: '3.5'
services:
  nginx:
    image: nginx:latest
    container_name: docker-nginx
    restart: always
    depends_on:
      - sandbox
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/sandbox.conf:/etc/nginx/conf.d/sandbox.conf
      - ./certificates/sandbox:/etc/nginx/certs/sandbox
      - ./wordpress/sandbox:/var/www/html
  
  sandbox:
    image: wordpress:php7.3-fpm
    container_name: docker-sandbox
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    volumes:
      - ./wordpress/sandbox:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker-phpmyadmin
    restart: always
    ports:
     - "8081:80"
    environment:
     - PMA_ARBITRARY=1
    volumes:
     - /sessions

volumes:
  db_data: