version: '3.8'
services:
  server:
    image: benlumia007/lamp:v1.0.0
    container_name: server
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "1025:1025"
      - "1080:1080"
      - "3306:3306"
    volumes:
      - ../.global:/srv/.global
      - ../certificates:/srv/certificates
      - ../config:/srv/config
      - ../provision:/app
      - ../databases:/srv/databases
      - ../sites:/srv/www
