version: '3.5'
services:
  apache:
    image: benlumia007/nginx:php7.2-fpm
    container_name: apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.global:/srv/.global
      - ../certificates:/srv/certificates
      - ../logs/nginx:/var/log/nginx
      - ../logs/php:/var/log/php
      - ../sites:/srv/www

  mysql:
    image: benlumia007/mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../.global:/srv/.global
      - ../databases:/srv/databases
      - db_data:/var/lib/mysql

  mailhog:
    image: benlumia007/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
