version: '3.5'
services:
  nginx:
    image: benlumia007/nginx:php7.2-fpm
    container_name: nginx
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.global:/srv/.global
      - ../app:/app
      - ../certificates:/srv/certificates
      - ../databases:/srv/databases
      - ../logs/nginx:/var/log/nginx
      - ../logs/php:/var/log/php
      - ../sites:/srv/www/
      - db_data:/var/lib/mysql

  mailhog:
    image: benlumia007/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
