version: '3.5'
services:
  apache2:
    image: benlumia007/apache2:php7.4
    container_name: apache2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.global:/srv/.global
      - ../certificates:/srv/certificates
      - ../config/apache2:/srv/config/apache2
      - ../config/phpmyadmin:/srv/config/phpmyadmin
      - ../config/default.yml:/srv/config/default.yml
      - ../logs/apache2:/var/log/apache2
      - ../logs/php:/var/log/php
      - ../provision/apache2:/app
      - ../sites:/srv/www

  mysql:
    image: benlumia007/mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../.global:/srv/.global
      - ../databases:/srv/databases
      - ../logs/mysql:/var/log/mysql
      - ../provision/mysql:/app

  mailhog:
    image: benlumia007/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"