version: '3.7'
services:
  server:
    image: benlumia007/lemp
    container_name: server
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ../.global:/srv/.global
      - ../certificates:/srv/certificates
      - ../config:/srv/config
      - ../logs:/srv/log
      - ../provision:/app
      - ../databases:/srv/databases
      - ../sites:/srv/www