version: '3.5'
services:
  nginx:
    image: ubuntu-lamp-stack
    container_name: nginx
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "9000"
    volumes:
      - ../.global:/srv/.global
      - ../app:/app
      - ../certificates:/srv/certificates
      - ../sites:/srv/www/

volumes:
  db_data:
