version: '3.5'
services:
  server:
    image: server
    container_name: server
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ../.global:/srv/.global
      - ../certificates:/srv/certificates
      - ../config:/srv/config
      - ../logs/apache2:/var/log/apache2
      - ../logs/php:/var/log/php
      - ../provision:/app
      - ../databases:/srv/databases
      - ../sites:/srv/www