# docker-setup.yml
#
# This is the main YAML formatted file which is done in spaces and not tabs, and whitespace.
# If you do not stick to the format. it will fail on provision.

# Important Note
#
# If you need to add a new site, copy the example and uncomment the lines and enter the site name.
# You wil then need to run when you use make create-sites.
sites:
  sandbox:
    provision: false
    repo: https://github.com/benlumia007/docker-for-wordpress-sites.git
    host:
      - sandbox.test

  # The following commented out site configuration will create a standard WordPress. Please remember
  # that whitespace is significant and spaces means different things
  # example:
  #  provision: false
  #  repo: https://github.com/benlumia007/docker-for-wordpress-sites.git
  #  host:
  #    - example.test

resources:
  - phpmyadmin
  - tls-ca
